// Every active public transport vehicle class in Australia.
// Images are loaded from Wikimedia Commons via Special:FilePath.

const vehicles = [
  // --- New South Wales -------------------------------------------------------
  {
    id: "waratah",
    name: "Waratah A & B sets",
    shortName: "Waratah",
    state: "NSW",
    city: "Sydney",
    mode: "train",
    rarity: "common",
    weight: 24,
    operator: "Sydney Trains",
    service: "2011-present",
    speed: "130 km/h",
    capacity: "~1,200",
    tagline: "The train you will almost certainly board in Sydney.",
    description:
      "With well over 500 carriages across two generations, the double-deck Waratah is the largest passenger fleet in Australia. If you tap on somewhere in suburban Sydney, odds are one of these turns up.",
    file: "Double image of A set and B set Waratahs.jpg",
    source: "https://en.wikipedia.org/wiki/Sydney_Trains_A_%26_B_sets",
  },
  {
    id: "millennium",
    name: "Millennium M set",
    shortName: "Millennium",
    state: "NSW",
    city: "Sydney",
    mode: "train",
    rarity: "rare",
    weight: 16,
    operator: "Sydney Trains",
    service: "2002-present",
    speed: "130 km/h",
    capacity: "~900",
    tagline: "The set with the famous power-up whine.",
    description:
      "Built in Cardiff, New South Wales for the new millennium, the M set introduced a generation of creature comforts to Sydney's double-deck fleet. Its distinctive traction sound is instantly recognisable to locals.",
    file: "M10approachingCentral.jpg",
    source: "https://en.wikipedia.org/wiki/Sydney_Trains_M_set",
  },
  {
    id: "oscar",
    name: "OSCAR H set",
    shortName: "OSCAR",
    state: "NSW",
    city: "Sydney",
    mode: "train",
    rarity: "rare",
    weight: 16,
    operator: "Sydney Trains",
    service: "2006-present",
    speed: "130 km/h",
    capacity: "~900",
    tagline: "Outer Suburban CARriage, friend of the South Coast.",
    description:
      "The OSCAR was designed for longer outer-suburban runs, with high-backed seating and big luggage racks. H sets are a staple of the South Coast Line between Sydney, Wollongong and Kiama.",
    file: "H48-Orange-Schofields-Oct2025.jpg",
    source: "https://en.wikipedia.org/wiki/Sydney_Trains_H_set",
  },
  {
    id: "tangara",
    name: "Tangara T set",
    shortName: "Tangara",
    state: "NSW",
    city: "Sydney",
    mode: "train",
    rarity: "common",
    weight: 24,
    operator: "Sydney Trains",
    service: "1988-present",
    speed: "115 km/h",
    capacity: "~1,200",
    tagline: "The wedge-faced workhorse since 1988.",
    description:
      "Tangara means 'to go' in Dharug, and these distinctive sloped-front double-deckers have been going for nearly four decades. They remain a core part of Sydney's suburban timetable.",
    file: "20230805 T27 passing through Banksia Railway Station.jpg",
    source: "https://en.wikipedia.org/wiki/Sydney_Trains_T_set",
  },
  {
    id: "mariyung",
    name: "Mariyung D set",
    shortName: "Mariyung",
    state: "NSW",
    city: "Sydney & Intercity",
    mode: "train",
    rarity: "epic",
    weight: 8,
    operator: "NSW TrainLink",
    service: "2023-present",
    speed: "130 km/h",
    capacity: "~1,200",
    tagline: "The new intercity fleet named for the emu.",
    description:
      "Mariyung is the Darug word for emu, and the D set replaced the much-loved V sets on the Blue Mountains, Central Coast and South Coast runs. Wide two-by-two seating and tray tables make it a long-haul commuter's friend.",
    file: "D44 DSC 0125 Cropped.jpg",
    source: "https://en.wikipedia.org/wiki/NSW_TrainLink_D_set",
  },
  {
    id: "xpt",
    name: "XPT",
    shortName: "XPT",
    state: "NSW",
    city: "Regional NSW",
    mode: "train",
    rarity: "legendary",
    weight: 3,
    operator: "NSW TrainLink",
    service: "1982-present",
    speed: "160 km/h",
    capacity: "~300",
    tagline: "Australia's rail speed icon since 1982.",
    description:
      "Based on the British InterCity 125, the XPT once set the Australian rail speed record at 193 km/h. It still runs the long hauls to Melbourne, Brisbane, Dubbo, Grafton and Casino — catch one while you can, replacements are coming.",
    file: "NSW XPT passenger train Galong, NSW.jpg",
    source: "https://en.wikipedia.org/wiki/New_South_Wales_XPT",
  },
  {
    id: "xplorer",
    name: "Xplorer",
    shortName: "Xplorer",
    state: "NSW",
    city: "Regional NSW",
    mode: "train",
    rarity: "rare",
    weight: 16,
    operator: "NSW TrainLink",
    service: "1993-present",
    speed: "145 km/h",
    capacity: "~150",
    tagline: "The diesel that reaches Canberra and Broken Hill.",
    description:
      "Xplorer railcars cover the regional routes the XPT can't, including Canberra, Griffith, Moree, Armidale and the marathon run to Broken Hill. Country travel with a buffet on board.",
    file: "NSW TrainLink Xplorer 2508.jpg",
    source: "https://en.wikipedia.org/wiki/New_South_Wales_Xplorer",
  },
  {
    id: "endeavour",
    name: "Endeavour railcar",
    shortName: "Endeavour",
    state: "NSW",
    city: "Regional NSW",
    mode: "train",
    rarity: "common",
    weight: 24,
    operator: "NSW TrainLink",
    service: "1994-present",
    speed: "145 km/h",
    capacity: "~190",
    tagline: "Short-haul diesel for the regional fringes.",
    description:
      "The Endeavour shares its body with the Xplorer but works shorter outer-regional runs like the Southern Highlands and South Coast beyond the wires. A dependable two-car diesel commuter.",
    file: "Endeavour Railcar - 2851, 2801.jpg",
    source: "https://en.wikipedia.org/wiki/Endeavour_railcar",
  },
  {
    id: "hunter",
    name: "Hunter railcar",
    shortName: "Hunter railcar",
    state: "NSW",
    city: "Newcastle",
    mode: "train",
    rarity: "common",
    weight: 24,
    operator: "NSW TrainLink",
    service: "2006-present",
    speed: "145 km/h",
    capacity: "~120",
    tagline: "The Hunter Valley's nimble two-car diesel.",
    description:
      "Hunter railcars shuttle between Newcastle, Maitland, Scone and Dungog. They are the smallest trains in the NSW TrainLink fleet and the backbone of the Hunter Line.",
    file: "Hunter railcars 2751 & 2701 (45512879812).jpg",
    source: "https://en.wikipedia.org/wiki/Hunter_railcar",
  },
  {
    id: "sydney-metro",
    name: "Sydney Metro Metropolis",
    shortName: "Metro Metropolis",
    state: "NSW",
    city: "Sydney",
    mode: "train",
    rarity: "epic",
    weight: 8,
    operator: "Metro Trains Sydney",
    service: "2019-present",
    speed: "100 km/h",
    capacity: "1,100",
    tagline: "Driverless, single-deck and built for frequency.",
    description:
      "Sydney Metro's six-car Alstom Metropolis trains operate automatically with wide doors and longitudinal seating. The fleet serves the North West, City and Bankstown corridors.",
    file: "Sydney Metro Alstom Metropolis Driverless Train1.jpg",
    source: "https://en.wikipedia.org/wiki/Sydney_Metro_Metropolis_Stock",
  },
  {
    id: "citadis-x05",
    name: "Citadis X05",
    shortName: "Citadis X05",
    state: "NSW",
    city: "Sydney",
    mode: "tram",
    rarity: "rare",
    weight: 16,
    operator: "Transdev Sydney Light Rail",
    service: "2019-present",
    speed: "80 km/h",
    capacity: "450 (coupled)",
    tagline: "Coupled pairs gliding down George Street.",
    description:
      "Running in permanently coupled 67-metre pairs, the Citadis X05 is among the longest trams in the world. It serves the L2 and L3 lines from Circular Quay to Randwick and Kingsford.",
    file: "New trams operating in George street Sydney CBD - late December 2019 - 49281061742.jpg",
    source: "https://en.wikipedia.org/wiki/CBD_and_South_East_Light_Rail",
  },
  {
    id: "urbos-sydney",
    name: "Sydney Urbos 3",
    shortName: "Sydney Urbos 3",
    state: "NSW",
    city: "Sydney",
    mode: "tram",
    rarity: "common",
    weight: 24,
    operator: "Transdev Sydney",
    service: "2014-present",
    speed: "80 km/h",
    capacity: "~200",
    tagline: "Inner West veteran, now in Parramatta too.",
    description:
      "CAF's Urbos 3 has worked the Inner West Light Rail from Central to Dulwich Hill since 2014, and new sets opened the Parramatta Light Rail in 2024. The quiet achiever of Sydney's tram revival.",
    file: "A tram (15860847401).jpg",
    source: "https://en.wikipedia.org/wiki/Inner_West_Light_Rail",
  },
  {
    id: "urbos-newcastle",
    name: "Newcastle Urbos 100",
    shortName: "Newcastle Urbos",
    state: "NSW",
    city: "Newcastle",
    mode: "tram",
    rarity: "rare",
    weight: 16,
    operator: "Newcastle Transport",
    service: "2019-present",
    speed: "70 km/h",
    capacity: "270",
    tagline: "Wire-free trams along the harbour.",
    description:
      "Newcastle's Urbos 100 trams run the 2.7 km line from Newcastle Interchange to the beach with no overhead wires at all, charging from onboard energy storage at each stop.",
    file: "Newcastle Light Rail Queens Wharf.jpg",
    source: "https://en.wikipedia.org/wiki/Newcastle_Light_Rail",
  },
  {
    id: "freshwater",
    name: "Freshwater-class ferry",
    shortName: "Freshwater ferry",
    state: "NSW",
    city: "Sydney",
    mode: "ferry",
    rarity: "legendary",
    weight: 3,
    operator: "Sydney Ferries",
    service: "1982-present",
    speed: "16 knots",
    capacity: "1,100",
    tagline: "The Manly ferry. Enough said.",
    description:
      "The mighty Freshwater class is the icon of Sydney Harbour, plowing across the Heads to Manly in any weather. Two vessels survive in weekend service after a public outcry saved them from retirement.",
    file: "Sydney Ferry Collaroy 1 - Nov 2008.jpg",
    source: "https://en.wikipedia.org/wiki/Freshwater-class_ferry",
  },
  {
    id: "first-fleet",
    name: "First Fleet-class ferry",
    shortName: "First Fleet ferry",
    state: "NSW",
    city: "Sydney",
    mode: "ferry",
    rarity: "rare",
    weight: 16,
    operator: "Sydney Ferries",
    service: "1984-present",
    speed: "11 knots",
    capacity: "393",
    tagline: "Nine little ships named for 1788.",
    description:
      "Each First Fleet-class catamaran carries the name of a ship from the 1788 First Fleet. They handle the inner-harbour runs to Taronga Zoo, Mosman, Balmain and beyond, and turn 40 still going strong.",
    file: "Scarborough, Pyrmont Bay, 2017 (01).jpg",
    source: "https://en.wikipedia.org/wiki/First_Fleet-class_ferry",
  },
  {
    id: "rivercat",
    name: "RiverCat-class ferry",
    shortName: "RiverCat",
    state: "NSW",
    city: "Sydney",
    mode: "ferry",
    rarity: "common",
    weight: 24,
    operator: "Sydney Ferries",
    service: "1992-present",
    speed: "22 knots",
    capacity: "230",
    tagline: "Shallow-draught speed up the Parramatta River.",
    description:
      "RiverCats were purpose-built to skim the shallow upper reaches of the Parramatta River, and each is named after a famous Australian sportswoman. The wash limits are strict; the views are not.",
    file: "STA Ferry Rivercat Catamaran Shane Gould arriving Parramatta Wharf.jpg",
    source: "https://en.wikipedia.org/wiki/RiverCat-class_ferry",
  },
  {
    id: "parramatta-class",
    name: "Parramatta River-class ferry",
    shortName: "Parramatta ferry",
    state: "NSW",
    city: "Sydney",
    mode: "ferry",
    rarity: "epic",
    weight: 8,
    operator: "Sydney Ferries",
    service: "2021-present",
    speed: "24 knots",
    capacity: "200",
    tagline: "The river fleet's newest generation.",
    description:
      "The Parramatta River class brought fresh hulls to the F3 river run, named for prominent Australians including scientists and Indigenous leaders. Low wash, high speed, and panoramic windows.",
    file: "Parramatta-Class ferry MV Frances Bodkin at Circular Quay.jpg",
    source: "https://en.wikipedia.org/wiki/Parramatta_River-class_ferry",
  },
  {
    id: "emerald-ferry",
    name: "Emerald-class ferry",
    shortName: "Emerald ferry",
    state: "NSW",
    city: "Sydney",
    mode: "ferry",
    rarity: "common",
    weight: 24,
    operator: "Sydney Ferries",
    service: "2017-present",
    speed: "26 knots",
    capacity: "400",
    tagline: "A catamaran built for the harbour commute.",
    description:
      "The Emerald class carries passengers across Sydney Harbour with bicycle storage, device charging and improved accessibility. Nine vessels span two generations.",
    file: "Vivid Sydney 2018 (12).jpg",
    source: "https://en.wikipedia.org/wiki/Emerald-class_ferry",
  },
  {
    id: "b-line",
    name: "B-Line double decker",
    shortName: "B-Line bus",
    state: "NSW",
    city: "Sydney",
    mode: "bus",
    rarity: "rare",
    weight: 16,
    operator: "Keolis Downer Northern Beaches",
    service: "2017-present",
    speed: "80 km/h",
    capacity: "~95",
    tagline: "Big yellow double deckers to the Northern Beaches.",
    description:
      "The B-Line brought European-style double-decker buses to the Mona Vale corridor, with turn-up-and-go frequency and famous yellow livery. Upstairs front seats are the unofficial prize.",
    file: "Keolis MAN A95 @ B1, Clarence Street (20231006a) (cropped).jpg",
    source: "https://en.wikipedia.org/wiki/B-Line_(Sydney)",
  },

  // --- Victoria ----------------------------------------------------------------
  {
    id: "comeng",
    name: "Comeng EMU",
    shortName: "Comeng",
    state: "VIC",
    city: "Melbourne",
    mode: "train",
    rarity: "common",
    weight: 24,
    operator: "Metro Trains Melbourne",
    service: "1981-present",
    speed: "115 km/h",
    capacity: "~1,000",
    tagline: "Melbourne's longest-serving electric survivor.",
    description:
      "The Comeng has hauled Melburnians since 1981 and is the elder statesman of the suburban fleet. Retirement is finally approaching as new trains arrive — every trip is borrowed time.",
    file: "Alstom Comeng 571M at Westona.jpg",
    source: "https://en.wikipedia.org/wiki/Comeng_(train)",
  },
  {
    id: "siemens-nexas",
    name: "Siemens Nexas",
    shortName: "Nexas",
    state: "VIC",
    city: "Melbourne",
    mode: "train",
    rarity: "common",
    weight: 24,
    operator: "Metro Trains Melbourne",
    service: "2003-present",
    speed: "115 km/h",
    capacity: "~900",
    tagline: "The smooth German of the suburban fleet.",
    description:
      "The Nexas brought modern AC traction and a distinctive smooth acceleration to Melbourne. The fleet works mainly through the Cross-City group to Werribee, Williamstown and Frankston.",
    file: "Siemens Nexas 789M Frankston to Williamstown service via Flinders Street at Seaford railway station Platform 1 (28 January 2026).jpg",
    source: "https://en.wikipedia.org/wiki/Siemens_Nexas",
  },
  {
    id: "xtrapolis-100",
    name: "X'Trapolis 100",
    shortName: "X'Trapolis 100",
    state: "VIC",
    city: "Melbourne",
    mode: "train",
    rarity: "common",
    weight: 24,
    operator: "Metro Trains Melbourne",
    service: "2002-present",
    speed: "130 km/h",
    capacity: "~900",
    tagline: "Backbone of the eastern suburbs.",
    description:
      "Melbourne's most numerous train, the X'Trapolis 100 dominates the Burnley and Clifton Hill groups out to Lilydale, Belgrave, Hurstbridge and Mernda. Later batches were assembled in Ballarat.",
    file: "210M Kananook.jpg",
    source: "https://en.wikipedia.org/wiki/X%27Trapolis_100",
  },
  {
    id: "hcmt",
    name: "High Capacity Metro Train",
    shortName: "HCMT",
    state: "VIC",
    city: "Melbourne",
    mode: "train",
    rarity: "epic",
    weight: 8,
    operator: "Metro Trains Melbourne",
    service: "2020-present",
    speed: "130 km/h",
    capacity: "1,380",
    tagline: "Seven cars through the Metro Tunnel.",
    description:
      "The HCMT is the biggest train Melbourne has ever run — a 160-metre, seven-car walk-through set built at Newport. It carries the load through the new Metro Tunnel between Sunbury and Cranbourne/Pakenham.",
    file: "HCMT set 9033 Westall to West Footscray service via Metro Tunnel at Footscray railway station Platform 2 (28 January 2026).jpg",
    source: "https://en.wikipedia.org/wiki/High_Capacity_Metro_Trains",
  },
  {
    id: "vlocity",
    name: "V/Line VLocity",
    shortName: "VLocity",
    state: "VIC",
    city: "Regional Victoria",
    mode: "train",
    rarity: "rare",
    weight: 16,
    operator: "V/Line",
    service: "2005-present",
    speed: "160 km/h",
    capacity: "Up to 224",
    tagline: "Purple regional speed from Dandenong.",
    description:
      "The VLocity is the fastest train in V/Line's fleet and a defining sight across regional Victoria. The diesel multiple units have been in continuous production for more than two decades.",
    file: "Vlocity train at lara victoria.jpg",
    source: "https://en.wikipedia.org/wiki/V/Line_VLocity",
  },
  {
    id: "sprinter",
    name: "V/Line Sprinter",
    shortName: "Sprinter",
    state: "VIC",
    city: "Regional Victoria",
    mode: "train",
    rarity: "common",
    weight: 24,
    operator: "V/Line",
    service: "1993-present",
    speed: "130 km/h",
    capacity: "~90 per car",
    tagline: "Single-car diesels doing the short hauls.",
    description:
      "Sprinters are V/Line's single-car railcars, often coupled in pairs or trios for shorter regional runs to Seymour, Shepparton and Stony Point. Simple, boxy and surprisingly quick.",
    file: "Sprinter 7007 up Seymour service at Coolaroo railway station Platform 1 (21 January 2026).jpg",
    source: "https://en.wikipedia.org/wiki/V/Line_Sprinter",
  },
  {
    id: "n-class",
    name: "V/Line N class",
    shortName: "N class",
    state: "VIC",
    city: "Regional Victoria",
    mode: "train",
    rarity: "rare",
    weight: 16,
    operator: "V/Line",
    service: "1985-present",
    speed: "115 km/h",
    capacity: "N set ~260",
    tagline: "Loco-hauled comfort on the long hauls.",
    description:
      "The N class diesel locomotives haul V/Line's traditional carriage sets on long-distance runs like Warrnambool and Albury. The last loco-hauled passenger workings in regular Victorian service.",
    file: "VLine N Class Locomotive N467.jpg",
    source: "https://en.wikipedia.org/wiki/V/Line_N_class",
  },
  {
    id: "a-class-tram",
    name: "A-class Melbourne tram",
    shortName: "A-class tram",
    state: "VIC",
    city: "Melbourne",
    mode: "tram",
    rarity: "common",
    weight: 24,
    operator: "Yarra Trams",
    service: "1984-present",
    speed: "70 km/h",
    capacity: "~105",
    tagline: "The compact classic of the inner city.",
    description:
      "The boxy A-class has rattled around Melbourne's inner suburbs for four decades. Short, high-floored and ubiquitous, it is the tram many Melburnians picture when they think 'tram'.",
    file: "A2.288 collins, 2023 (01).jpg",
    source: "https://en.wikipedia.org/wiki/A-class_Melbourne_tram",
  },
  {
    id: "b2-class-tram",
    name: "B2-class Melbourne tram",
    shortName: "B2-class tram",
    state: "VIC",
    city: "Melbourne",
    mode: "tram",
    rarity: "common",
    weight: 24,
    operator: "Yarra Trams",
    service: "1988-present",
    speed: "70 km/h",
    capacity: "~180",
    tagline: "The big articulated bruiser of the 80s.",
    description:
      "The two-section B2 was Melbourne's first mass-produced articulated tram and still holds down busy routes like the 86 and 96. A whole generation learned to commute aboard one.",
    file: "B2-class tram -2131 operating Route 1 to South Melbourne Beach on Swanston Street crossing Collins Street, Melbourne.jpg",
    source: "https://en.wikipedia.org/wiki/B-class_Melbourne_tram",
  },
  {
    id: "c-class-tram",
    name: "C-class Melbourne tram",
    shortName: "C-class tram",
    state: "VIC",
    city: "Melbourne",
    mode: "tram",
    rarity: "common",
    weight: 24,
    operator: "Yarra Trams",
    service: "2001-present",
    speed: "70 km/h",
    capacity: "~140",
    tagline: "Melbourne's first low-floor tram.",
    description:
      "The three-section Citadis 202 introduced level boarding to Melbourne in 2001. The fleet of 36 works route 109 between Box Hill and Port Melbourne.",
    file: "C.3021 collins, 2023 (01).jpg",
    source: "https://en.wikipedia.org/wiki/C-class_Melbourne_tram",
  },
  {
    id: "c2-class-tram",
    name: "C2-class Melbourne tram",
    shortName: "C2 'Bumblebee'",
    state: "VIC",
    city: "Melbourne",
    mode: "tram",
    rarity: "epic",
    weight: 8,
    operator: "Yarra Trams",
    service: "2008-present",
    speed: "70 km/h",
    capacity: "~200",
    tagline: "Five Bumblebees, borrowed from France.",
    description:
      "Just five C2-class Citadis trams exist in Melbourne, originally leased from the French city of Mulhouse. Their yellow fronts earned them the nickname 'Bumblebees' — spotting one is a genuine event.",
    file: "C2.5123 bourke, 2014.jpg",
    source: "https://en.wikipedia.org/wiki/C2-class_Melbourne_tram",
  },
  {
    id: "d-class-tram",
    name: "D-class Melbourne tram",
    shortName: "D-class Combino",
    state: "VIC",
    city: "Melbourne",
    mode: "tram",
    rarity: "common",
    weight: 24,
    operator: "Yarra Trams",
    service: "2002-present",
    speed: "70 km/h",
    capacity: "~180",
    tagline: "Siemens Combinos in three and five sections.",
    description:
      "The D1 and D2 Combinos brought German low-floor design to routes like the 19, 58 and 72. The five-section D2s are the larger and more common sight.",
    file: "D2.5016 elizabeth, 2023 (01).jpg",
    source: "https://en.wikipedia.org/wiki/D-class_Melbourne_tram",
  },
  {
    id: "e-class",
    name: "E-class Melbourne tram",
    shortName: "E-class tram",
    state: "VIC",
    city: "Melbourne",
    mode: "tram",
    rarity: "common",
    weight: 24,
    operator: "Yarra Trams",
    service: "2013-present",
    speed: "80 km/h",
    capacity: "210",
    tagline: "Melbourne's biggest production tram.",
    description:
      "The five-section E-class is Melbourne's longest tram in regular service. Built in Dandenong, its low floor and high capacity suit the network's busiest routes.",
    file: "Melbourne Tram E-Class 6007.jpg",
    source: "https://en.wikipedia.org/wiki/E-class_Melbourne_tram",
  },
  {
    id: "g-class",
    name: "G-class Melbourne tram",
    shortName: "G-class tram",
    state: "VIC",
    city: "Melbourne",
    mode: "tram",
    rarity: "legendary",
    weight: 3,
    operator: "Yarra Trams",
    service: "2026 rollout",
    speed: "80 km/h",
    capacity: "150",
    tagline: "Melbourne's next generation, made in Dandenong.",
    description:
      "The low-floor G-class is based on Alstom's Flexity 2 platform and built for Melbourne's famous tram network. Battery storage and regenerative braking are designed to reduce peak power demand.",
    file: "G-class tram mockup at Alstom warehouse in Melbourne, Tullamarine (53413292470).jpg",
    source: "https://en.wikipedia.org/wiki/G-class_Melbourne_tram",
  },
  {
    id: "w8-class",
    name: "W8-class Melbourne tram",
    shortName: "W8 City Circle",
    state: "VIC",
    city: "Melbourne",
    mode: "tram",
    rarity: "legendary",
    weight: 3,
    operator: "Yarra Trams",
    service: "1936-present",
    speed: "60 km/h",
    capacity: "~90",
    tagline: "A 1930s legend still in timetabled service.",
    description:
      "The maroon W8s on the free City Circle route are rebuilt W-class trams dating back to the 1930s — among the oldest trams in scheduled service anywhere on Earth. Wooden seats, clanging gong, pure Melbourne.",
    file: "W8 class tram -961 operating a route 35 City Circle service on Spring Street crossing Collins Street, Melbourne.jpg",
    source: "https://en.wikipedia.org/wiki/W-class_Melbourne_tram",
  },
  {
    id: "z3-class-tram",
    name: "Z3-class Melbourne tram",
    shortName: "Z3-class tram",
    state: "VIC",
    city: "Melbourne",
    mode: "tram",
    rarity: "rare",
    weight: 16,
    operator: "Yarra Trams",
    service: "1979-present",
    speed: "70 km/h",
    capacity: "~105",
    tagline: "The last of the high-floor originals.",
    description:
      "The Z3 has served Melbourne since 1979 and is now in its farewell years as new G-class trams arrive. Every orange-doored survivor you spot is living history.",
    file: "Z class at Maribyrnong termius.jpg",
    source: "https://en.wikipedia.org/wiki/Z-class_Melbourne_tram",
  },
  {
    id: "westgate-punt",
    name: "Westgate Punt",
    shortName: "Westgate Punt",
    state: "VIC",
    city: "Melbourne",
    mode: "ferry",
    rarity: "rare",
    weight: 16,
    operator: "Westgate Punt",
    service: "Commuter service",
    speed: "8 knots",
    capacity: "~12",
    tagline: "The tiniest vessel in Victorian public transport.",
    description:
      "This little punt ferries cyclists and pedestrians across the Yarra beneath the West Gate Bridge, linking Spotswood with Fishermans Bend. Quite possibly Australia's most obscure timetabled service.",
    file: "Westgate Punt boat passing under the West Gate Bridge, Melbourne.jpg",
    source: "https://en.wikipedia.org/wiki/Westgate_Punt",
  },
  {
    id: "kinetic-melbourne",
    name: "Kinetic Melbourne Volgren",
    shortName: "Melbourne bus",
    state: "VIC",
    city: "Melbourne",
    mode: "bus",
    rarity: "common",
    weight: 24,
    operator: "Kinetic Melbourne",
    service: "2022-present",
    speed: "80 km/h",
    capacity: "~60",
    tagline: "The orange workhorse of Melbourne's bus web.",
    description:
      "Kinetic runs Melbourne's biggest bus franchise with hundreds of Volgren-bodied buses built in Dandenong. The PTV orange livery threads through every suburb the trains and trams miss.",
    file: "Kinetic Melbourne Bus Route 202 at University of Melbourne.jpg",
    source: "https://en.wikipedia.org/wiki/Buses_in_Melbourne",
  },

  // --- Queensland ----------------------------------------------------------------
  {
    id: "ngr",
    name: "New Generation Rollingstock",
    shortName: "NGR",
    state: "QLD",
    city: "Brisbane",
    mode: "train",
    rarity: "legendary",
    weight: 3,
    operator: "Queensland Rail",
    service: "2017-present",
    speed: "140 km/h",
    capacity: "964",
    tagline: "Six cars of South East Queensland muscle.",
    description:
      "Queensland Rail's largest electric fleet links Brisbane with the Gold Coast, Airport, Redcliffe and more. Its walk-through six-car formation makes the NGR one of the network's most recognisable modern trains.",
    file: "New Generation Rollingstock 736 Sunshine Railway Station Bilsen Rd Geebung P1040861.jpg",
    source: "https://en.wikipedia.org/wiki/New_Generation_Rollingstock",
  },
  {
    id: "smu",
    name: "Suburban Multiple Unit",
    shortName: "SMU",
    state: "QLD",
    city: "Brisbane",
    mode: "train",
    rarity: "common",
    weight: 24,
    operator: "Queensland Rail",
    service: "1994-present",
    speed: "100 km/h",
    capacity: "~470",
    tagline: "Three generations of Brisbane's daily grinders.",
    description:
      "The SMU 200, 220 and 260 series have carried Brisbane commuters since the mid-90s. With the original EMUs retired, these are now the elders of the City network.",
    file: "266Corinda.jpg",
    source: "https://en.wikipedia.org/wiki/Suburban_Multiple_Unit",
  },
  {
    id: "imu",
    name: "Interurban Multiple Unit",
    shortName: "IMU",
    state: "QLD",
    city: "Brisbane & Gold Coast",
    mode: "train",
    rarity: "rare",
    weight: 16,
    operator: "Queensland Rail",
    service: "1996-present",
    speed: "140 km/h",
    capacity: "~450",
    tagline: "The airport and Gold Coast flyer.",
    description:
      "IMUs were built for the longer interurban dashes to the Gold Coast and Brisbane Airport, with luggage racks and higher speeds than their suburban SMU cousins.",
    file: "IMU 184.jpg",
    source: "https://en.wikipedia.org/wiki/Interurban_multiple_unit",
  },
  {
    id: "electric-tilt",
    name: "Electric Tilt Train",
    shortName: "Electric Tilt Train",
    state: "QLD",
    city: "Brisbane–Rockhampton",
    mode: "train",
    rarity: "legendary",
    weight: 3,
    operator: "Queensland Rail",
    service: "1998-present",
    speed: "160 km/h",
    capacity: "~360",
    tagline: "Holder of the Australian rail speed record: 210 km/h.",
    description:
      "Queensland's Electric Tilt Train leans into curves on the narrow gauge North Coast line and once hit 210 km/h on test — still the fastest any train has gone in Australia. It runs Brisbane to Rockhampton and Bundaberg.",
    file: "City of Maryborough Platform 10 Roma Street Station Brisbane P1280919 (cropped).jpg",
    source: "https://en.wikipedia.org/wiki/Electric_Tilt_Train",
  },
  {
    id: "diesel-tilt",
    name: "Diesel Tilt Train",
    shortName: "Spirit of Queensland",
    state: "QLD",
    city: "Brisbane–Cairns",
    mode: "train",
    rarity: "epic",
    weight: 8,
    operator: "Queensland Rail",
    service: "2003-present",
    speed: "160 km/h",
    capacity: "314",
    tagline: "1,681 km of coastline with lie-flat RailBeds.",
    description:
      "The Diesel Tilt Train runs the marathon Spirit of Queensland service from Brisbane to Cairns, with airline-style RailBeds for the overnight haul. One of the great Australian rail journeys.",
    file: "Spirit Of Queensland - Diesel Tilt Train.jpg",
    source: "https://en.wikipedia.org/wiki/Diesel_Tilt_Train",
  },
  {
    id: "gulflander",
    name: "Gulflander",
    shortName: "Gulflander",
    state: "QLD",
    city: "Normanton",
    mode: "train",
    rarity: "legendary",
    weight: 3,
    operator: "Queensland Rail",
    service: "1891 line, RM93 railmotor",
    speed: "40 km/h",
    capacity: "~40",
    tagline: "From nowhere to nowhere, once a week.",
    description:
      "The Gulflander trundles 152 km between Normanton and Croydon in the Gulf Country on a line isolated from every other railway in Australia. The 1950 railmotor is the rarest catch in this entire collection's real-world inspiration.",
    file: "Railmotor93.jpg",
    source: "https://en.wikipedia.org/wiki/Gulflander",
  },
  {
    id: "spirit-outback",
    name: "Spirit of the Outback",
    shortName: "Spirit of the Outback",
    state: "QLD",
    city: "Brisbane–Longreach",
    mode: "train",
    rarity: "epic",
    weight: 8,
    operator: "Queensland Rail",
    service: "1993-present",
    speed: "100 km/h",
    capacity: "~160",
    tagline: "Sleepers and a club car to Longreach.",
    description:
      "Twice a week the Spirit of the Outback hauls sleeping cars 1,325 km from Brisbane deep into western Queensland. Loco-hauled, leisurely and a true outback institution.",
    file: "Spirit of the Outback Bilsen Rd Geebung P1420326.jpg",
    source: "https://en.wikipedia.org/wiki/Spirit_of_the_Outback",
  },
  {
    id: "g-link",
    name: "G:link Flexity 2",
    shortName: "G:link Flexity 2",
    state: "QLD",
    city: "Gold Coast",
    mode: "tram",
    rarity: "rare",
    weight: 16,
    operator: "Keolis Downer",
    service: "2014-present",
    speed: "70 km/h",
    capacity: "309",
    tagline: "Blue-sky light rail for the Gold Coast.",
    description:
      "The seven-section Flexity 2 is a 100 percent low-floor tram built for the Gold Coast's long, linear urban corridor. Its surfboard racks are a particularly local touch.",
    file: "GCLR Set 9 at Broadwater Parklands 2014-09-28.jpg",
    source: "https://en.wikipedia.org/wiki/G:link",
  },
  {
    id: "brisbane-metro",
    name: "Brisbane Metro lighTram 25",
    shortName: "Brisbane Metro",
    state: "QLD",
    city: "Brisbane",
    mode: "bus",
    rarity: "epic",
    weight: 8,
    operator: "Transport for Brisbane",
    service: "2025-present",
    speed: "90 km/h",
    capacity: "150",
    tagline: "A 24.5 metre electric bus with metro ambitions.",
    description:
      "The bi-articulated HESS lighTram 25 uses rapid charging and all-door boarding on Brisbane's busways. It is the unusual, unmistakable centrepiece of the city's Metro service.",
    file: "Brisbane Metro bus testing on the Northern Busway, Brisbane, February 2024 P1001852.jpg",
    source: "https://en.wikipedia.org/wiki/Brisbane_Metro",
  },
  {
    id: "citycat",
    name: "CityCat",
    shortName: "CityCat",
    state: "QLD",
    city: "Brisbane",
    mode: "ferry",
    rarity: "rare",
    weight: 16,
    operator: "Transport for Brisbane",
    service: "1996-present",
    speed: "25 knots",
    capacity: "~170",
    tagline: "Brisbane's river highway at 25 knots.",
    description:
      "CityCat catamarans sprint along the Brisbane River from UQ to Northshore Hamilton, each carrying an Aboriginal name for a place on the river. The commute Brisbane shows off to visitors.",
    file: "CityCat Binkinba and CityCat Meeandah approach North Quay Ferry Terminal Brisbane P1190681.jpg",
    source: "https://en.wikipedia.org/wiki/RiverCity_Ferries",
  },
  {
    id: "cityhopper",
    name: "CityHopper",
    shortName: "CityHopper",
    state: "QLD",
    city: "Brisbane",
    mode: "ferry",
    rarity: "common",
    weight: 24,
    operator: "Transport for Brisbane",
    service: "2012-present",
    speed: "10 knots",
    capacity: "~48",
    tagline: "The free red ferry of the inner river.",
    description:
      "The red CityHopper monohulls loop the inner-city reach of the Brisbane River for free, from North Quay to Sydney Street. Slow, breezy and completely gratis.",
    file: "CityHopper ferry passing by the City Botanic Gardens, Brisbane.jpg",
    source: "https://en.wikipedia.org/wiki/RiverCity_Ferries",
  },

  // --- Western Australia -----------------------------------------------------------
  {
    id: "a-series",
    name: "Transperth A-series",
    shortName: "A-series",
    state: "WA",
    city: "Perth",
    mode: "train",
    rarity: "common",
    weight: 24,
    operator: "Transperth",
    service: "1991-present",
    speed: "110 km/h",
    capacity: "~500",
    tagline: "The trains that brought electricity to Perth.",
    description:
      "The A-series electrified Perth's network in 1991 and has served every line since. With C-series replacements arriving, the originals are entering their twilight years.",
    file: "Transperth Trains A-Set 209 Midland Line 2 car set (5680733149).jpg",
    source: "https://en.wikipedia.org/wiki/Transperth_A-series_train",
  },
  {
    id: "b-series",
    name: "Transperth B-series",
    shortName: "B-series",
    state: "WA",
    city: "Perth",
    mode: "train",
    rarity: "common",
    weight: 24,
    operator: "Transperth",
    service: "2004-present",
    speed: "130 km/h",
    capacity: "~890",
    tagline: "Three cars flying down the freeway median.",
    description:
      "The B-series was built for the long, fast Mandurah and Joondalup lines, where it cruises at 130 km/h down the middle of the freeway. The backbone of Perth's north-south spine.",
    file: "TransperthTrains-Bseries-Closeup.JPG",
    source: "https://en.wikipedia.org/wiki/Transperth_B-series_train",
  },
  {
    id: "c-series",
    name: "Transperth C-series",
    shortName: "C-series",
    state: "WA",
    city: "Perth",
    mode: "train",
    rarity: "epic",
    weight: 8,
    operator: "Transperth",
    service: "2024-present",
    speed: "130 km/h",
    capacity: "1,184",
    tagline: "The X'Trapolis built back home in WA.",
    description:
      "Assembled at Bellevue, the C-series returned passenger train manufacturing to Western Australia. Six-car sets entered service on the Yanchep and Mandurah lines in 2024.",
    file: "Transperth C-series train at Canning Bridge Station, October 2024.jpg",
    source: "https://en.wikipedia.org/wiki/Transperth_C-series_train",
  },
  {
    id: "prospector",
    name: "Prospector",
    shortName: "Prospector",
    state: "WA",
    city: "Perth–Kalgoorlie",
    mode: "train",
    rarity: "epic",
    weight: 8,
    operator: "Transwa",
    service: "2004-present",
    speed: "160 km/h",
    capacity: "~108",
    tagline: "The fastest diesel railcar in Australia.",
    description:
      "The Prospector covers the 655 km from East Perth to the Goldfields at up to 160 km/h, making it Australia's fastest diesel train. Meals served at your seat as the wheatbelt blurs past.",
    file: "The Prospector streamliner.JPG",
    source: "https://en.wikipedia.org/wiki/Prospector_(train)",
  },
  {
    id: "avonlink",
    name: "AvonLink",
    shortName: "AvonLink",
    state: "WA",
    city: "Perth–Northam",
    mode: "train",
    rarity: "rare",
    weight: 16,
    operator: "Transwa",
    service: "2004-present",
    speed: "160 km/h",
    capacity: "~100",
    tagline: "The Avon Valley's commuter secret.",
    description:
      "Sister to the Prospector, the AvonLink railcar threads the scenic Avon Valley between Midland, Toodyay and Northam. One of the most obscure timetables in the country — perfect collector bait.",
    file: "Avonlink Bellevue.jpg",
    source: "https://en.wikipedia.org/wiki/AvonLink",
  },
  {
    id: "perth-ferry",
    name: "Transperth ferry",
    shortName: "Perth ferry",
    state: "WA",
    city: "Perth",
    mode: "ferry",
    rarity: "common",
    weight: 24,
    operator: "Transperth",
    service: "Elizabeth Quay–South Perth",
    speed: "10 knots",
    capacity: "~100",
    tagline: "Australia's shortest ferry commute.",
    description:
      "Perth's only ferry route crosses the Swan River from Elizabeth Quay to South Perth in about seven minutes. The vessels include MV Shelley Taylor-Smith, named for the champion marathon swimmer.",
    file: "MV Shelley Taylor-Smith crossing the Swan River, February 2023 03.jpg",
    source: "https://en.wikipedia.org/wiki/Transperth",
  },
  {
    id: "perth-cat",
    name: "Perth CAT bus",
    shortName: "Perth CAT",
    state: "WA",
    city: "Perth",
    mode: "bus",
    rarity: "common",
    weight: 24,
    operator: "Transperth",
    service: "1996-present",
    speed: "80 km/h",
    capacity: "~60",
    tagline: "Free loops around the city, forever.",
    description:
      "The Central Area Transit buses loop Perth, Fremantle and Joondalup city centres completely free of charge, colour-coded by route. A Perth institution since the 90s.",
    file: "Perth CAT 2013 Volgren CR228L bodied Volvo B7RLE diesel TP2142.jpg",
    source: "https://en.wikipedia.org/wiki/Perth_Central_Area_Transit",
  },

  // --- South Australia ----------------------------------------------------------------
  {
    id: "acity",
    name: "Adelaide A-City 4000",
    shortName: "A-City 4000",
    state: "SA",
    city: "Adelaide",
    mode: "train",
    rarity: "rare",
    weight: 16,
    operator: "Adelaide Metro",
    service: "2014-present",
    speed: "110 km/h",
    capacity: "540",
    tagline: "South Australia's electric flagship.",
    description:
      "The three-car A-City is the only operational electric train class in South Australia. Built in Dandenong, it serves the Gawler, Seaford and Flinders lines.",
    file: "Adelaide Metro 4000 Class at Seaford.jpg",
    source: "https://en.wikipedia.org/wiki/Adelaide_Metro_4000_class",
  },
  {
    id: "3000-class",
    name: "Adelaide Metro 3000 class",
    shortName: "3000 class",
    state: "SA",
    city: "Adelaide",
    mode: "train",
    rarity: "common",
    weight: 24,
    operator: "Adelaide Metro",
    service: "1988-present",
    speed: "100 km/h",
    capacity: "~105 per car",
    tagline: "The diesel 'Jumbo juniors' of Adelaide.",
    description:
      "The 3000 class diesel railcars work the non-electrified lines to Belair, Outer Harbor and Grange. They have defined the look of Adelaide rail for nearly four decades.",
    file: "Adelaide Metro 3000 Class Railcar at Elizabeth.jpg",
    source: "https://en.wikipedia.org/wiki/Adelaide_Metro_3000_class",
  },
  {
    id: "flexity-adelaide",
    name: "Adelaide Flexity Classic",
    shortName: "Flexity Classic",
    state: "SA",
    city: "Adelaide",
    mode: "tram",
    rarity: "rare",
    weight: 16,
    operator: "Adelaide Metro",
    service: "2006-present",
    speed: "70 km/h",
    capacity: "~180",
    tagline: "The tram that revived the Glenelg line.",
    description:
      "Adelaide's Flexity Classics replaced the beloved 1929 H-class trams on the historic Glenelg line and now run through the city to the Entertainment Centre. Germany via Bay 2 Beach.",
    file: "Adelaide Metro Glenelg Tram (Flexity Classic).JPG",
    source: "https://en.wikipedia.org/wiki/Flexity_Classic",
  },
  {
    id: "citadis-adelaide",
    name: "Adelaide Citadis 302",
    shortName: "Citadis Adelaide",
    state: "SA",
    city: "Adelaide",
    mode: "tram",
    rarity: "rare",
    weight: 16,
    operator: "Adelaide Metro",
    service: "2009-present",
    speed: "70 km/h",
    capacity: "~190",
    tagline: "Secondhand from Madrid, right at home in Adelaide.",
    description:
      "Adelaide's Citadis 302 trams were bought secondhand from Madrid, where they had barely been used. They now share the city line with the Flexity fleet — a genuine European import story.",
    file: "Adelaide Metro Citadis 302 tram from Glenelg at Morphett Road tram stop.jpg",
    source: "https://en.wikipedia.org/wiki/Trams_in_Adelaide",
  },
  {
    id: "obahn",
    name: "O-Bahn busway bus",
    shortName: "O-Bahn",
    state: "SA",
    city: "Adelaide",
    mode: "bus",
    rarity: "epic",
    weight: 8,
    operator: "Adelaide Metro",
    service: "1986-present",
    speed: "100 km/h",
    capacity: "~100",
    tagline: "Buses on rails-that-aren't-rails at 100 km/h.",
    description:
      "Adelaide's O-Bahn is the world's longest and fastest guided busway: buses lock onto a concrete track and barrel through the Torrens Gorge at 100 km/h, then drive off the end like a normal bus. There is nothing else like it in Australia.",
    file: "(AUS-South Australia) Torrens Transit 808 SA-Heavy Vehicle-SB-37-GS M44 2025-12-14.jpg",
    source: "https://en.wikipedia.org/wiki/O-Bahn_Busway",
  },

  // --- Tasmania ------------------------------------------------------------------------
  {
    id: "spirit-tasmania",
    name: "Spirit of Tasmania",
    shortName: "Spirit of Tasmania",
    state: "TAS",
    city: "Devonport–Geelong",
    mode: "ferry",
    rarity: "legendary",
    weight: 3,
    operator: "TT-Line (Tasmanian Government)",
    service: "1985-present",
    speed: "~26 knots",
    capacity: "~1,400",
    tagline: "The ship that is Tasmania's highway.",
    description:
      "With no trains and no bridge, the Spirit of Tasmania ferries are the island's lifeline across Bass Strait, sailing overnight between Devonport and Geelong. The biggest 'vehicle' in this entire collection.",
    file: "Spirit of Tasmania Port Melbourne.jpg",
    source: "https://en.wikipedia.org/wiki/Spirit_of_Tasmania",
  },
  {
    id: "metro-tasmania",
    name: "Metro Tasmania Bustech XDI",
    shortName: "Metro Tasmania bus",
    state: "TAS",
    city: "Hobart",
    mode: "bus",
    rarity: "common",
    weight: 24,
    operator: "Metro Tasmania",
    service: "Hobart, Launceston & Burnie",
    speed: "80 km/h",
    capacity: "~65",
    tagline: "The whole network, on rubber tyres.",
    description:
      "Tasmania has no passenger trains, so Metro Tasmania's green-and-white buses are the state's entire urban public transport system, climbing Hobart's famously steep hills daily.",
    file: "Metro Tasmania -855 (MET855) Bustech XDI - Cummins Bustech (52092799024).jpg",
    source: "https://en.wikipedia.org/wiki/Metro_Tasmania",
  },

  // --- Northern Territory ----------------------------------------------------------------
  {
    id: "darwinbus",
    name: "Darwinbus Volgren",
    shortName: "Darwin bus",
    state: "NT",
    city: "Darwin",
    mode: "bus",
    rarity: "common",
    weight: 24,
    operator: "Darwinbus",
    service: "Darwin & Palmerston",
    speed: "80 km/h",
    capacity: "~70",
    tagline: "Tropical routes through the Top End.",
    description:
      "Darwin's public transport runs entirely on buses, linking the city with Palmerston and Casuarina through the build-up heat and the wet season alike. The Territory's only entry — and a must-have for completionists.",
    file: "Darwinbus - Volgren CR228L bodied Mercedes Benz OC500LE.jpg",
    source: "https://en.wikipedia.org/wiki/Darwinbus",
  },

  // --- Australian Capital Territory ---------------------------------------------------------
  {
    id: "canberra-urbos",
    name: "Canberra CAF Urbos 3",
    shortName: "Canberra Urbos 3",
    state: "ACT",
    city: "Canberra",
    mode: "tram",
    rarity: "rare",
    weight: 16,
    operator: "Canberra Metro",
    service: "2019-present",
    speed: "70 km/h",
    capacity: "207",
    tagline: "The capital's red light rail workhorse.",
    description:
      "Canberra's five-section CAF Urbos 3 trams connect Gungahlin with Civic. They launched the capital's first modern light rail service in April 2019.",
    file: "Urbos 3 leaving the Alinga Street light rail stop July 2021 (2).jpg",
    source: "https://en.wikipedia.org/wiki/Light_rail_in_Canberra",
  },
  {
    id: "canberra-ebus",
    name: "Transport Canberra electric bus",
    shortName: "Canberra e-bus",
    state: "ACT",
    city: "Canberra",
    mode: "bus",
    rarity: "rare",
    weight: 16,
    operator: "Transport Canberra",
    service: "2020-present",
    speed: "80 km/h",
    capacity: "~70",
    tagline: "Battery buses for a zero-emissions capital.",
    description:
      "Transport Canberra is converting its whole fleet to zero emissions, led by battery-electric buses like the one nicknamed 'Elektra'. Quiet streets, big ambitions.",
    file: "Transport Canberra bus no. 809, nicknamed 'Elektra'.jpg",
    source: "https://en.wikipedia.org/wiki/Transport_Canberra",
  },
];

const stateInfo = {
  NSW: {
    name: "New South Wales",
    blurb: "Double-deck heavy rail, driverless metro, three light rail systems and a harbour full of ferries.",
  },
  VIC: {
    name: "Victoria",
    blurb: "The world's largest tram network, suburban electrics and fast purple regional rail.",
  },
  QLD: {
    name: "Queensland",
    blurb: "Tilt trains up the coast, CityCats on the river and an electric busway giant.",
  },
  WA: {
    name: "Western Australia",
    blurb: "Freeway-median electrics and the fastest diesel railcar in the country.",
  },
  SA: {
    name: "South Australia",
    blurb: "Diesel and electric railcars, trams to Glenelg and the unique O-Bahn guided busway.",
  },
  TAS: {
    name: "Tasmania",
    blurb: "No passenger trains here — Bass Strait ships and an all-bus network instead.",
  },
  NT: {
    name: "Northern Territory",
    blurb: "Tropical bus routes around Darwin and Palmerston in the Top End.",
  },
  ACT: {
    name: "Australian Capital Territory",
    blurb: "A red light rail line and a fast-growing electric bus fleet.",
  },
};
